much much better daemon

diff --git a/usr/sbin/closestalledprocessesd b/usr/sbin/closestalledprocessesd
--- a/usr/sbin/closestalledprocessesd
+++ b/usr/sbin/closestalledprocessesd
@@ -123,7 +123,7 @@ main(){
 
     # }}}
     # sleep times: 120 = 2 minutes, 300 = 5 minutes
-    sleeptime=240
+    sleeptime=300
 
     if [[ "$arg" = "onetime" ]] ; then
         is_onetime=1
@@ -132,59 +132,78 @@ main(){
     while true
     do
         # scan for annoying processes (sorted by cpu usage)
-        top -b -n 1 | head -n 18 | tail -n 11 | while read -r pid user priority nice memvrit memresident memshared status cpu_usage mem_usage time_minutes command
+        LC_ALL=C top -b -n 1 | head -n 200 | tail -n +8 | while read -r pid user priority nice memvrit memresident memshared status cpu_usage mem_usage time_minutes command
         do
             cpu_usage="${cpu_usage%.*}"
             mem_usage="${mem_usage%.*}"
 
-            time_minutes="$(( ( ${time_minutes%%:*} * 60 ) + $( echo "${time_minutes%.*}" | sed -e 's|^.*:||g' -e 's|^0||g' ) ))"
+            # break the loop from here, we don't need to check more than this
+            if [[ "$cpu_usage" -lt 10 ]] ; then
+                break
+            fi
+
             time_minutes="${time_minutes%.*}"
+            time_minutes="$(( $(( $(( ${time_minutes%%:*} * 60 )) + ${time_minutes##*:} )) / 60 ))"
 
             #
             # rules
             #
 
-            # gvfsd-daemon sometimes blocks sucking cpu cycles
-            if [[ "${command}" = "gvfsd-metadata" ]] && [[ "${time_minutes}" -gt 5 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
-                logger "$(basename $0) - annoying process detected (${command}), minutes: ${time_minutes}, cpu usage: ${cpu_usage}, at pid: ${pid} "
-                kill_process "$pid" "${status}" "$command"
-            fi
+            #echo -e "D: checking command: $command with minutes: $time_minutes" 1>&2
 
-            # tumblerd sucking around
-            if [[ "${command}" = "tumblerd" ]] && [[ "${time_minutes}" -gt 5 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
-                logger "$(basename $0) - annoying process detected (${command}), minutes: ${time_minutes}, cpu usage: ${cpu_usage}, at pid: ${pid} "
-                kill_process "$pid" "${status}" "$command"
-            fi
+            case "$command" in
+                gvfsd-metadata)
+                    # gvfsd-daemon sometimes blocks sucking cpu cycles
+                    if [[ "${time_minutes}" -ge 5 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
+                        logger "$(basename $0) - annoying process detected (${command}), minutes: ${time_minutes}, cpu usage: ${cpu_usage}, at pid: ${pid} "
+                        kill_process "$pid" "${status}" "$command"
+                    fi
 
-            # mpg123 sometimes got stucked eating cpu
-            if [[ "${command}" = "mpg123" ]] && [[ "${time_minutes}" -gt 15 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
-                logger "$(basename $0) - annoying process detected (${command}), minutes: ${time_minutes}, cpu usage: ${cpu_usage}, at pid: ${pid} "
-                kill_process "$pid" "${status}" "$command"
-            fi
+                    ;;
+                tumblerd)
+                    # tumblerd sucking around
+                    if [[ "${time_minutes}" -ge 5 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
+                        logger "$(basename $0) - annoying process detected (${command}), minutes: ${time_minutes}, cpu usage: ${cpu_usage}, at pid: ${pid} "
+                        kill_process "$pid" "${status}" "$command"
+                    fi
 
-            # zombies ? kill them with a chainsaw!
-            #if [[ "$status" = *Z* ]] && [[ "${time_minutes}" -gt 1 ]] ; then
-            #kill_process "$pid" "${status}" "$command" "killing zombie process"
-            #fi
+                    ;;
+                mpg123*)
+                    # mpg123 sometimes got stucked eating cpu
+                    if [[ "${time_minutes}" -ge 15 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
+                        logger "$(basename $0) - annoying process detected (${command}), minutes: ${time_minutes}, cpu usage: ${cpu_usage}, at pid: ${pid} "
+                        kill_process "$pid" "${status}" "$command"
+                    fi
 
+                    ;;
+                vlc|mplayer|gmplayer)
+                    if [[ "${time_minutes}" -ge 180 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
+                        # more than 3 hours with a video player consuming cpu == player stuck
+                        kill_process "$pid" "${status}" "$command"
+                    fi
+
+                    ;;
+                # blackisted ones:  yeah, we know that they sucks, and we love them on this way :/
+                songbird-bin|chromium|iceweasel*|firefox*)
+                        # songbird:  its a simply greedy eater of resoureces
+                        # chromium:  when we play videos cpu becomes high, and we could have it running since long time
+                        true
+                    ;;
+
+                *)
+                    if [[ "${time_minutes}" -gt 200 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
+                        logger "$(basename $0) - PLEASE REPORT TO ELIVE: annoying process detected (${command}) sucking cpu for more than 3 hours at pid: ${pid}, error ? we should kill these ones too ?"
+                    fi
+                    ;;
+
+            esac
         done
-        # scan for specific processes
-        top -b -n 1 | grep "tumblerd" | while read -r pid user priority nice memvrit memresident memshared status cpu_usage mem_usage time_minutes command
-        do
-            cpu_usage="${cpu_usage%,*}"
-            time_minutes="$(( ( ${time_minutes%%:*} * 60 ) + $( echo "${time_minutes%.*}" | sed -e 's|^.*:||g' ) ))"
-            command="${command}"
 
-            # tumblerd stalled ?
-            if [[ "${command}" = "tumblerd" ]] && [[ "${time_minutes}" -gt 5 ]] ; then
-                logger "$(basename $0) - stalled process detected (${command}), minutes: ${time_minutes}, cpu usage: (not required to know), at pid: ${pid} | from detecting time in top"
-                kill_process "$pid" "${status}" "$command"
-            fi
 
-            # kill it from a different time check, since seems to not have very good reliable info
-            killall --older-than 1h tumblerd 2>/dev/null
-            logger "$(basename $0) - stalled process detected (${command}), minutes: ${time_minutes}, cpu usage: (not required to know), at pid: ${pid} | from killall --older-than 1h"
-        done
+        # always kill long tumblerd's
+        if killall --older-than 1h tumblerd 2>/dev/null ; then
+            logger "$(basename $0) - stalled process detected (tumblerd), minutes: ${time_minutes}, cpu usage: (not required to know), at pid: (unknown) | from killall --older-than 1h"
+        fi
 
         # zombies
         kill_processes_zombie
