show btrfs errors

diff --git a/usr/bin/elive-health b/usr/bin/elive-health
--- a/usr/bin/elive-health
+++ b/usr/bin/elive-health
@@ -288,6 +288,49 @@ main(){
                 el_config_save "conf_count_sectors_pending"
             fi
         fi
+
+        # btrfs reports
+        if dmesg | LC_ALL=C grep -E "BTRFS error.*(fixed up error at logical|unable to fixup)" ; then
+            btrfs_dmesg_errors="$( dmesg | LC_ALL=C grep -E "BTRFS error.*(fixed up error at logical|unable to fixup)" | sed -e 's|^.*] BTRFS |BTRFS |g' )"
+            if [[ "$btrfs_dmesg_errors" != "$conf_btrfs_dmesg_errors" ]] ; then
+                local message_btrfs_title message_btrfs_1 message_btrfs_knowmore
+                message_btrfs_title="$( printf "$( eval_gettext "Data integrity errors" )" "" )"
+                message_btrfs_knowmore="$( printf "$( eval_gettext "Know more" )" "" )"
+                message_btrfs_1="$( eval_gettext "Your filesystem has detected errors that it was unable to fix. This could lead to data loss. Use the BTRFS check and scrub tools to know more" )"
+
+                if dmesg | grep -qs "BTRFS error.* unable to fixup)" ; then
+                    # import to show the unrecoverable errors
+                    result="$( el_notify wait bomb "$message_btrfs_title" "${message_btrfs_1}\n\n$( echo "${btrfs_dmesg_errors}" | sort -u )" --action=open="$message_btrfs_knowmore" )"
+                    if [[ "$result" == "open" ]] ; then
+                        is_know_more=1
+                    fi
+
+                else
+                    if ! $guitool --warning --title="$message_btrfs_title" --cancel-label="$( eval_gettext "Know More" )" \
+                        --text="$( eval_gettext "BTRFS detected errors in your system. This filesystem is self-healing, but it is recommended to back up your data and run a filesystem check to prevent data loss." )\n\n$btrfs_dmesg_errors" ; then
+                        is_know_more=1
+                    fi
+                fi
+
+                if ((is_know_more)) ; then
+                    gksu -- urxvt -e bash -c '
+                        while read -ru 3 dir
+                        do
+                            echo "$dir" | awk "{if ($2 == "btrfs") print $2}" | while read -r mountpoint
+                            do
+                                echo "Status for ${mountpoint}:"
+                                btrfs scrub status "$mountpoint" | tail -n 3
+                                # btrfs check --force --repair "$mountpoint"
+                            done
+                        done 3<<< "$( cat "/proc/mounts" )"
+                        '
+                fi
+
+                # save to not repeat
+                conf_btrfs_dmesg_errors="$btrfs_dmesg_errors"
+                el_config_save "conf_btrfs_dmesg_errors"
+            fi
+        fi
     fi
 
 
